In [ ]:
# Import Pandas library and Read 'Appt_No_Show.csv' file

import pandas as pd

no_show = pd.read_csv('Appt_No_Show.csv')

In [24]:
# Quick review on dataset
no_show.info()

<class 'pandas.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PatientId       110527 non-null  float64
 1   AppointmentID   110527 non-null  int64
 2   Gender          110527 non-null  str
 3   ScheduledDay    110527 non-null  str
 4   AppointmentDay  110527 non-null  str
 5   Age             110527 non-null  int64
 6   Neighbourhood   110527 non-null  str
 7   Scholarship     110527 non-null  int64
 8   Hipertension    110527 non-null  int64
 9   Diabetes        110527 non-null  int64
 10  Alcoholism      110527 non-null  int64
 11  Handcap         110527 non-null  int64
 12  SMS_received    110527 non-null  int64
 13  No-show         110527 non-null  str
dtypes: float64(1), int64(8), str(5)
memory usage: 11.8 MB

In [ ]:
# Create a copy file before cleaning up the original dataset. This will help generate a cleaned version while maintaining the original file
no_show_cleaned = no_show.copy()

In [37]:
# Check to see if there is duplicate
dup = no_show_cleaned.duplicated().sum()
print(dup)

# Confirmed that no duplicate exists

0

In [25]:
# Find minimum age and maximum age
min_age = no_show_cleaned['Age'].min()
max_age = no_show_cleaned['Age'].max()

print("Minimum Age:", min_age)
print("Maximum Age:", max_age)

# Found some outliers (Age <0 and Age >100)

Minimum Age: 1
Maximum Age: 99

In [26]:
# Exclude the age outliers from dataset
no_show_cleaned = no_show_cleaned[(no_show_cleaned['Age']>0) & (no_show_cleaned['Age']<100)]
no_show_cleaned.info()

<class 'pandas.DataFrame'>
Index: 106971 entries, 0 to 110526
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PatientId       106971 non-null  float64
 1   AppointmentID   106971 non-null  int64
 2   Gender          106971 non-null  str
 3   ScheduledDay    106971 non-null  datetime64[us, UTC]
 4   AppointmentDay  106971 non-null  datetime64[us, UTC]
 5   Age             106971 non-null  int64
 6   Neighbourhood   106971 non-null  str
 7   Scholarship     106971 non-null  int64
 8   Hypertension    106971 non-null  int64
 9   Diabetes        106971 non-null  int64
 10  Alcoholism      106971 non-null  int64
 11  Handicap        106971 non-null  int64
 12  SMS_received    106971 non-null  int64
 13  No_show         106971 non-null  int64
 14  WaitDays        106971 non-null  int64
dtypes: datetime64[us, UTC](2), float64(1), int64(10), str(2)
memory usage: 13.1 MB

In [ ]:
# Convert ScheduledDay and AppointmentDay columns to date type
date_cols = ["ScheduledDay", "AppointmentDay"]
for col in date_cols:
    no_show_cleaned[col] = pd.to_datetime(no_show_cleaned[col], errors="coerce").dt.normalize()

In [ ]:
# Confirm the data type change for ScheduledDay and AppointmentDay
no_show_cleaned.head()

In [27]:
# Creat a new columm for WaitDays
no_show_cleaned["WaitDays"] = (no_show_cleaned["AppointmentDay"] - no_show_cleaned["ScheduledDay"]).dt.days
no_show_cleaned.head(10)

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hypertension,Diabetes,Alcoholism,Handicap,SMS_received,No_show,WaitDays
0,2.987250e+13,5642903,F,2016-04-29 00:00:00+00:00,2016-04-29 00:00:00+00:00,62,JARDIM DA PENHA,0,1,0,0,0,0,0,0
1,5.589978e+14,5642503,M,2016-04-29 00:00:00+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,0,0,0,0,0,0,0
2,4.262962e+12,5642549,F,2016-04-29 00:00:00+00:00,2016-04-29 00:00:00+00:00,62,MATA DA PRAIA,0,0,0,0,0,0,0,0
3,8.679512e+11,5642828,F,2016-04-29 00:00:00+00:00,2016-04-29 00:00:00+00:00,8,PONTAL DE CAMBURI,0,0,0,0,0,0,0,0
4,8.841186e+12,5642494,F,2016-04-29 00:00:00+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,1,1,0,0,0,0,0
5,9.598513e+13,5626772,F,2016-04-27 00:00:00+00:00,2016-04-29 00:00:00+00:00,76,REPÚBLICA,0,1,0,0,0,0,0,2
6,7.336882e+14,5630279,F,2016-04-27 00:00:00+00:00,2016-04-29 00:00:00+00:00,23,GOIABEIRAS,0,0,0,0,0,0,1,2
7,3.449833e+12,5630575,F,2016-04-27 00:00:00+00:00,2016-04-29 00:00:00+00:00,39,GOIABEIRAS,0,0,0,0,0,0,1,2
8,5.639473e+13,5638447,F,2016-04-29 00:00:00+00:00,2016-04-29 00:00:00+00:00,21,ANDORINHAS,0,0,0,0,0,0,0,0
9,7.812456e+13,5629123,F,2016-04-27 00:00:00+00:00,2016-04-29 00:00:00+00:00,19,CONQUISTA,0,0,0,0,0,0,0,2

In [29]:
# Find any outlier in WaitDays. WaitDays should be always equal to 0 or greater than 0
no_show_cleaned['WaitDays'].min()

np.int64(0)

In [ ]:
# Exclude the WaitDays outliers from dataset
no_show_cleaned = no_show_cleaned[(no_show_cleaned['WaitDays']>=0)]
no_show_cleaned.info()

In [30]:
# Modify column names for no_show, hypertension, and handicap

no_show_cleaned = no_show_cleaned.rename(columns={"No-show":"No_show"})
no_show_cleaned = no_show_cleaned.rename(columns={"Hipertension":"Hypertension"})
no_show_cleaned = no_show_cleaned.rename(columns={"Handcap":"Handicap"})

no_show_cleaned.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hypertension,Diabetes,Alcoholism,Handicap,SMS_received,No_show,WaitDays
0,2.987250e+13,5642903,F,2016-04-29 00:00:00+00:00,2016-04-29 00:00:00+00:00,62,JARDIM DA PENHA,0,1,0,0,0,0,0,0
1,5.589978e+14,5642503,M,2016-04-29 00:00:00+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,0,0,0,0,0,0,0
2,4.262962e+12,5642549,F,2016-04-29 00:00:00+00:00,2016-04-29 00:00:00+00:00,62,MATA DA PRAIA,0,0,0,0,0,0,0,0
3,8.679512e+11,5642828,F,2016-04-29 00:00:00+00:00,2016-04-29 00:00:00+00:00,8,PONTAL DE CAMBURI,0,0,0,0,0,0,0,0
4,8.841186e+12,5642494,F,2016-04-29 00:00:00+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,1,1,0,0,0,0,0

In [ ]:
# Convert No_show from Yes/No to 1/0 for analysis
no_show_cleaned['No_show'] = no_show_cleaned['No_show'].replace({'Yes':1, 'No':0})
no_show_cleaned['No_show'] = no_show_cleaned['No_show'].astype(int)
no_show_cleaned.head(5)

In [ ]:
no_show_cleaned.info()

In [31]:
# Find any correlation between different factors and no_show pattern using Pearson correlation coefficient

corr_scholarship = no_show_cleaned["Scholarship"].corr(no_show_cleaned["No_show"])
corr_SMS = no_show_cleaned["SMS_received"].corr(no_show_cleaned["No_show"])
corr_HTN = no_show_cleaned["Hypertension"].corr(no_show_cleaned["No_show"])
corr_DM = no_show_cleaned["Diabetes"].corr(no_show_cleaned["No_show"])
corr_Alcohol = no_show_cleaned["Alcoholism"].corr(no_show_cleaned["No_show"])
corr_Handicap = no_show_cleaned["Handicap"].corr(no_show_cleaned["No_show"])
print("Correlation between scholarship and No_Show:", corr_scholarship)
print("Correlation between SMS_received and No_Show:", corr_SMS)
print("Correlation between Hypertension and No_Show:", corr_HTN)
print("Correlation between Diabetes and No_Show:", corr_DM)
print("Correlation between Alcoholism and No_Show:", corr_Alcohol)
print("Correlation between Handicap and No_Show:", corr_Handicap)

Correlation between scholarship and No_Show: 0.029411863276454123
Correlation between SMS_received and No_Show: 0.12737653837637486
Correlation between Hypertension and No_Show: -0.037219462869973005
Correlation between Diabetes and No_Show: -0.015899315575300832
Correlation between Alcoholism and No_Show: -0.0004968119634202503
Correlation between Handicap and No_Show: -0.006862558744356628

In [32]:
# Find any correlation between Gender and no_show pattern using Chi-square test

import pandas as pd
from scipy.stats import chi2_contingency

# Create contingency table
contingency_table = pd.crosstab(
    no_show_cleaned['Gender'],
    no_show_cleaned['No_show']
)

# Run Chi-square test
chi2, p, dof, expected = chi2_contingency(contingency_table)

print("Chi-square statistic:", chi2)
print("Degrees of freedom:", dof)
print("p-value:", p)

Chi-square statistic: 1.0903741834344975
Degrees of freedom: 1
p-value: 0.29638831679734734

In [33]:
# Check final output
no_show_cleaned.head(10)

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hypertension,Diabetes,Alcoholism,Handicap,SMS_received,No_show,WaitDays
0,2.987250e+13,5642903,F,2016-04-29 00:00:00+00:00,2016-04-29 00:00:00+00:00,62,JARDIM DA PENHA,0,1,0,0,0,0,0,0
1,5.589978e+14,5642503,M,2016-04-29 00:00:00+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,0,0,0,0,0,0,0
2,4.262962e+12,5642549,F,2016-04-29 00:00:00+00:00,2016-04-29 00:00:00+00:00,62,MATA DA PRAIA,0,0,0,0,0,0,0,0
3,8.679512e+11,5642828,F,2016-04-29 00:00:00+00:00,2016-04-29 00:00:00+00:00,8,PONTAL DE CAMBURI,0,0,0,0,0,0,0,0
4,8.841186e+12,5642494,F,2016-04-29 00:00:00+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,1,1,0,0,0,0,0
5,9.598513e+13,5626772,F,2016-04-27 00:00:00+00:00,2016-04-29 00:00:00+00:00,76,REPÚBLICA,0,1,0,0,0,0,0,2
6,7.336882e+14,5630279,F,2016-04-27 00:00:00+00:00,2016-04-29 00:00:00+00:00,23,GOIABEIRAS,0,0,0,0,0,0,1,2
7,3.449833e+12,5630575,F,2016-04-27 00:00:00+00:00,2016-04-29 00:00:00+00:00,39,GOIABEIRAS,0,0,0,0,0,0,1,2
8,5.639473e+13,5638447,F,2016-04-29 00:00:00+00:00,2016-04-29 00:00:00+00:00,21,ANDORINHAS,0,0,0,0,0,0,0,0
9,7.812456e+13,5629123,F,2016-04-27 00:00:00+00:00,2016-04-29 00:00:00+00:00,19,CONQUISTA,0,0,0,0,0,0,0,2

In [ ]:
# Export a cleaned file to CSV for SQL analysis
no_show_cleaned.to_csv("Appt_No_Show_cleaned.csv", index=False)